# Generated by Django 2.1.5 on 2019-03-06 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': '用户信息'},
        ),
    ]
