# Generated by Django 2.1.5 on 2019-02-24 06:02

import ckeditor_uploader.fields
from django.db import migrations, models
import read_statistics.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='正文')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('last_updated_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
            ],
            options={
                'ordering': ['-created_time'],
            },
            bases=(models.Model, read_statistics.models.ReadNumExpandMethod),
        ),
        migrations.CreateModel(
            name='BlogType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=15, verbose_name='分类')),
            ],
        ),
    ]
