# Generated by Django 2.1.5 on 2019-03-02 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object_list_all',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Object_name', models.CharField(max_length=40, verbose_name='目标名称')),
                ('Object_alias_1', models.CharField(blank=True, max_length=30, verbose_name='目标别名1')),
                ('Object_alias_2', models.CharField(blank=True, max_length=30, verbose_name='目标别名2')),
                ('Obj_Type', models.CharField(blank=True, max_length=30, verbose_name='目标类型')),
                ('Obj_source', models.CharField(blank=True, max_length=30, verbose_name='目标来源')),
                ('Observer', models.CharField(max_length=30, verbose_name='观测者')),
                ('Obs_program', models.CharField(blank=True, max_length=30, verbose_name='观测项目')),
                ('Obj_RA', models.FloatField(max_length=30, verbose_name='目标赤经')),
                ('Obj_DEC', models.FloatField(max_length=30, verbose_name='目标赤纬')),
                ('Obj_Epoch', models.IntegerField(default=2000, verbose_name='历元')),
                ('Obj_Error', models.FloatField(default=0, max_length=30, verbose_name='误差')),
                ('Group_ID', models.CharField(max_length=30, verbose_name='设备群')),
                ('Unit_ID', models.CharField(max_length=30, verbose_name='设备编号')),
                ('Observation_type', models.CharField(default='man', max_length=30, verbose_name='观测类型')),
                ('Observation_strategy', models.CharField(default='pointing', max_length=30, verbose_name='观测策略')),
                ('Obs_date_begin', models.DateField(max_length=30, verbose_name='观测起始日期')),
                ('Obs_date_end', models.DateField(max_length=30, verbose_name='观测结束日期')),
                ('Obs_day_interval', models.IntegerField(default=1, verbose_name='观测频次')),
                ('imgtype', models.CharField(default='object', max_length=30, verbose_name='图像类型')),
                ('filter', models.CharField(max_length=30, verbose_name='波段')),
                ('expdur', models.CharField(max_length=30, verbose_name='曝光时间')),
                ('delay', models.CharField(default=0, max_length=30, verbose_name='曝光间隔')),
                ('frmcnt', models.IntegerField(verbose_name='曝光幅数')),
                ('prioriy', models.IntegerField(default=20, verbose_name='优先级')),
                ('run_name', models.IntegerField(default=1, verbose_name='曝光轮次')),
                ('note', models.CharField(blank=True, max_length=30, verbose_name='观测说明')),
                ('Obs_stage', models.CharField(choices=[('0', 'current'), ('1', 'past'), ('2', 'future'), ('3', 'removed')], default='current', max_length=30, verbose_name='观测阶段')),
                ('mode', models.CharField(choices=[('0', 'test'), ('1', 'observation')], default='observation', max_length=30, verbose_name='模式')),
            ],
            options={
                'verbose_name': '观测目标列表总表',
                'verbose_name_plural': '观测目标列表总表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Object_list_current',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Obs_date_current', models.DateField(max_length=30, verbose_name='观测日期')),
                ('Obs_timewindow_begin', models.DateTimeField(max_length=30, verbose_name='可观测时间窗口起始时间')),
                ('Obs_timewindow_end', models.DateTimeField(max_length=30, verbose_name='可观测时间窗口结束时间')),
                ('Obs_complete_stage', models.CharField(choices=[('0', 'scheduled'), ('1', 'completed'), ('2', 'canceled')], max_length=30, verbose_name='观测完成状态')),
                ('mode', models.CharField(choices=[('0', 'test'), ('1', 'observation')], max_length=30, verbose_name='模式')),
                ('Object_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datum.Object_list_all')),
            ],
            options={
                'verbose_name': '待观测目标列表',
                'verbose_name_plural': '待观测目标列表',
            },
        ),
    ]
