# Generated by Django 2.1.5 on 2019-03-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object_list_current',
            name='Obs_complete_stage',
            field=models.CharField(choices=[('0', 'scheduled'), ('1', 'completed'), ('2', 'canceled')], max_length=30, verbose_name='观测完成状态'),
        ),
    ]
