# Generated by Django 2.1.5 on 2019-03-02 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datum', '0002_auto_20190303_0145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='object_list_all',
            options={'ordering': ['prioriy'], 'verbose_name': '观测目标列表总表', 'verbose_name_plural': '观测目标列表总表'},
        ),
        migrations.AlterField(
            model_name='object_list_all',
            name='Obs_date_begin',
            field=models.DateField(default=datetime.date.today, max_length=30, verbose_name='观测起始日期'),
        ),
        migrations.AlterField(
            model_name='object_list_all',
            name='Obs_stage',
            field=models.CharField(choices=[('0', 'current'), ('1', 'past'), ('2', 'future'), ('3', 'removed')], default=0, max_length=30, verbose_name='观测阶段'),
        ),
        migrations.AlterField(
            model_name='object_list_all',
            name='mode',
            field=models.CharField(choices=[('0', 'observation'), ('1', 'test')], default=0, max_length=30, verbose_name='模式'),
        ),
    ]
