# Generated by Django 2.1.5 on 2019-03-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datum', '0002_auto_20190312_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects',
            name='Observation_type',
            field=models.CharField(choices=[('Mon', 'Mon'), ('ObA', 'ObA'), ('ObM', 'ObM'), ('GOA', 'GOA'), ('GOM', 'GOM'), ('ToM', 'ToM'), ('ROt', 'ROt'), ('Man', 'Man')], default='Man', max_length=30, verbose_name='观测类型'),
        ),
    ]
