# Generated by Django 2.1.5 on 2019-03-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datum', '0002_useraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraction',
            name='action_type',
            field=models.CharField(choices=[(0, '增加'), (1, '删除'), (2, '修改')], max_length=30, verbose_name='修改类型'),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='username',
            field=models.CharField(max_length=30, verbose_name='用户名称'),
        ),
    ]
