# Generated by Django 2.1.5 on 2019-03-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datum', '0003_auto_20190312_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects',
            name='Group_ID',
            field=models.CharField(choices=[('XL001', 'XL001'), ('XL002', 'XL002'), ('XL003', 'XL003')], max_length=30, verbose_name='设备群'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='Unit_ID',
            field=models.CharField(choices=[('001', '001'), ('002', '002'), ('003', '003'), ('004', '004')], max_length=30, verbose_name='设备编号'),
        ),
    ]
