# Generated by Django 2.1.5 on 2019-03-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datum', '0003_auto_20190304_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraction',
            name='action_time',
            field=models.DateTimeField(verbose_name='修改时间'),
        ),
    ]
