# Generated by Django 2.1.5 on 2019-03-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datum', '0004_auto_20190312_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects',
            name='Obj_DEC',
            field=models.CharField(max_length=30, verbose_name='目标赤纬'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='Obj_Error',
            field=models.CharField(default='0.0|0.0', max_length=30, verbose_name='误差'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='Obj_RA',
            field=models.CharField(max_length=30, verbose_name='目标赤经'),
        ),
    ]
