# Generated by Django 2.1.5 on 2019-03-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datum', '0005_auto_20190304_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraction',
            name='username',
            field=models.CharField(max_length=30, verbose_name='用户名'),
        ),
    ]
