# Generated by Django 2.1.5 on 2019-03-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datum', '0006_auto_20190304_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='object_list_all',
            name='is_delete',
            field=models.CharField(choices=[(0, 'PASS'), (1, 'DELETE')], default=0, max_length=30, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='object_list_all',
            name='Obs_stage',
            field=models.CharField(choices=[(0, 'current'), (1, 'past'), (2, 'future')], default=0, max_length=30, verbose_name='观测阶段'),
        ),
        migrations.AlterField(
            model_name='object_list_all',
            name='mode',
            field=models.CharField(choices=[(0, 'observation'), (1, 'test')], default=0, max_length=30, verbose_name='模式'),
        ),
        migrations.AlterField(
            model_name='object_list_current',
            name='Obs_complete_stage',
            field=models.CharField(choices=[(0, 'scheduled'), (1, 'completed'), (2, 'canceled')], max_length=30, verbose_name='观测完成状态'),
        ),
    ]
