# Generated by Django 2.1.5 on 2019-03-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datum', '0009_auto_20190305_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object_list_all',
            name='Obs_stage',
            field=models.CharField(choices=[('current', 'current'), ('past', 'past'), ('future', 'future'), ('removed', 'removed')], default='current', max_length=30, verbose_name='观测阶段'),
        ),
        migrations.AlterField(
            model_name='object_list_all',
            name='mode',
            field=models.CharField(choices=[('observation', 'observation'), ('test', 'test')], default='observation', max_length=30, verbose_name='模式'),
        ),
    ]
