# Generated by Django 2.1.5 on 2019-03-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datum', '0010_auto_20190305_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraction',
            name='action_type',
            field=models.CharField(choices=[('增加', '增加'), ('删除', '删除'), ('修改', '修改')], max_length=30, verbose_name='修改类型'),
        ),
    ]
